export const foodList = [
	{
		key: "0",
		name: "The Ovenstory Pizza",
		rating: 4,
		price: 600,
		type: "Non-Veg",
		dishType: "Pizza",
	},
	{
		key: "1",
		name: "The Fries King Popcorn",
		rating: 5,
		price: 200,
		type: "Non-Veg",
		dishType: "Chicken",
	},
	{
		key: "2",
		name: "The Momo way",
		rating: 4,
		price: 250,
		type: "Veg",
		dishType: "Momos",
	},
	{
		key: "3",
		name: "The Meat Momo way",
		rating: 5,
		price: 300,
		type: "Non-Veg",
		dishType: "Momos",
	},
	{
		key: "4",
		name: "The Dreamland Coke",
		rating: 3,
		price: 150,
		type: "Veg",
		dishType: "Beverage",
	},
	{
		key: "5",
		name: "Yomato Special Indian Thali",
		rating: 4,
		price: 750,
		type: "Non-Veg",
		dishType: "Indian",
	},
	{
		key: "6",
		name: "The Hornstreet Creams",
		rating: 2,
		price: 300,
		type: "Non-Veg",
		dishType: "Dessert",
	},
	{
		key: "7",
		name: "The Shawshank Biryani",
		rating: 5,
		price: 700,
		type: "Non-Veg",
		dishType: "Biryani",
	},
	{
		key: "8",
		name: "The Samurai Biryani",
		rating: 4,
		price: 420,
		type: "Veg",
		dishType: "Biryani",
	},
	{
		key: "9",
		name: "The Bengali Voj",
		rating: 5,
		price: 350,
		type: "Non-Veg",
		dishType: "Bengali",
	},
	{
		key: "10",
		name: "The Chinese SiFu",
		rating: 4,
		price: 400,
		type: "Non-Veg",
		dishType: "Chinese",
	},
];
